name: 'Install Dependencies'
description: 'Install dependencies, fetching from cache when possible'
inputs:
  node-version:
    description: the version of Node.js to install
    default: 22.21.1

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        version: 9.15.9
        cache: true

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install NPM Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
