export default [
  ['#root/*', './'],
  ['#lib/*', './lib'],
  ['#utils', './lib/utils/index.js'],
  ['#polyfills', './lib/env/polyfills/index.js'],
  ['#build', './lib/build/dispatcher/index.js'],
  ['#bundlers', './lib/build/bundlers/index.js'],
  ['#notations/*', './lib/notations'],
  ['#namespaces', './lib/notations/namespaces.js'],
  ['#typedef', './lib/notations/typedef.js'],
  ['#env', './lib/env/index.js'],
  ['#platform', './lib/platform/index.js'],
  ['#constants', './lib/constants/index.js'],
  ['#commands', './lib/commands/index.js'],
];
