/* eslint-disable */
const html = `<!DOCTYPE html>
<body>
  <h1>Hello world</h1>
  <p>This markup was generated by Azion - Edge Functions.</p>
</body>`;

/**
 *
 * @param request
 */
async function handleRequest(request) {
  return new Response(html, {
    headers: {
      'content-type': 'text/html;charset=UTF-8',
    },
  });
}

addEventListener('fetch', (event) => event.respondWith(handleRequest(event.request)));
