import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/app/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Redirect Permanent Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          <h1>Redirect Permanent Page</h1>
        </div>
      </main>
    </>
  );
}

export const runtime = "experimental-edge";
