name: Gen JSOC and Update Function

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]
    branches:
      - stage
env:
  HUSKY: 0

jobs:
  publish-jsdoc:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SO deps
        run: apk add curl git bash jq

      - name: Install dependencies
        run: npm install

      - name: Run task:docsx
        run: npm run task:docs

      - name: List files
        run: ls

      - name: Build JSDOCS
        run: |
          cd jsdoc/edge-functions/$(jq -r ".version" package.json)
          vulcan build --preset html --mode deliver

      - name: Download Azion CLI
        run: |
          cd jsdoc/edge-functions/$(jq -r ".version" package.json) 
          curl https://downloads.azion.com/linux/x86_64/azioncli -o azioncli && chmod +x azioncli

      - name: Create YML file to Azion CLI
        run: |
          cd jsdoc/edge-functions/$(jq -r ".version" package.json)
          mkdir ~/.config/ && touch ~/.config/azioncli.yaml

      - name: Configure Azion CLI
        run: ./azioncli configure -t ${{ secrets.RTM_TOKEN }}

      - name: Define application settings
        run: >
          echo $(jq 
          --arg funcid ${{ secrets.VULCAN_DOCS_EDGE_FUNCTION_ID }} 
          --arg appid ${{ secrets.VULCAN_DOCS_EDGE_APPLICATION_ID}} 
          --arg domainid ${{secrets.VULCAN_DOCS_DOMAIN_ID}} 
          '.name = "Console PK - Production"
          | .function.id = ($funcid|tonumber)
          | .application.id = ($appid|tonumber)
          | .domain.id = ($domainid|tonumber)'
          azion/azion.json) > azion/azion.json

      - name: Deploy
        run: |
          cd jsdoc/edge-functions/$(jq -r ".version" package.json)
          ./azioncli edge_applications publish
