name: Release (Minor/Patch)

on:
  push:
    branches:
      - dev
jobs:
  publish-release:
    strategy:
      matrix:
        node-version: [19.x]
        os: [ubuntu-latest]

    name: Release - ${{ matrix.os }} - Node v${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: yarn install
      - name: Create Release
        run: npx semantic-release -e ./releaserc.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
