name: OSV-Scanner PR Scan

on:
  pull_request:
    branches: [main, stage]
  merge_group:
    branches: [main, stage]

permissions: {}

jobs:
  scan-pr:
    permissions:
      # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
      actions: read
      # Require writing security events to upload SARIF file to security tab
      security-events: write
      # Only need to read contents
      contents: read
    uses: 'google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@8deb546fdb875b9996d27d4950be7312dac076a1' # v2.5.0
