name: Deploy Platform Kit (PRODUCTION)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  HUSKY: 0

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: node:18-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SO deps
        run: apk add curl git bash jq

      - name: Install dependencies
        run: yarn install

      - name: Run task:docs
        run: yarn task:docs

      - name: Change directory
        run: cd jsdoc/edge-functions/$(jq -r ".version" package.json)

      - name: Download Azion CLI
        run: curl https://downloads.azion.com/linux/x86_64/azioncli -o azioncli && chmod +x azioncli

      - name: Configure Azion CLI
        run: ./azioncli configure -t ${{ secrets.RTM_TOKEN }}

      - name: Define application settings
        run: >
          echo $(jq 
          --arg funcid ${{secrets.VULCAN_DOCS_EDGE_FUNCTION_ID}} 
          --arg appid ${{secrets.VULCAN_DOCS_EDGE_APPLICATION_ID}} 
          --arg domainid ${{secrets.VULCAN_DOCS_DOMAIN_ID}} 
          '.name = "Console PK - Production"
          | .function.id = ($funcid|tonumber)
          | .application.id = ($appid|tonumber)
          | .domain.id = ($domainid|tonumber)'
          azion/azion.json) > azion/azion.json

      - name: Deploy Edge Application
        run: ./azioncli edge_applications publish
