name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Compile
        run: pnpm build

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
          commit: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          NODE_ENV: 'production'
          # for when you create a new package
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
