name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Compile
        run: pnpm build

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          NODE_ENV: 'production'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
