name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # npm provenance
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Compile
        run: pnpm build

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          publish-script: pnpm exec changeset publish
          commit-message: 'chore: version packages'
        env:
          NODE_ENV: 'production'
          # for when you create a new package
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
