name: E2E Tests

on:
  pull_request:
    branches: [main, stage]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  tests-e2e:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 80
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Puppeteer Chrome (host runner)
        run: pnpm -F @aziontech/bundler exec puppeteer browsers install chrome

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run E2E tests
        run: pnpm -F @aziontech/bundler test:e2e
