name: E2E Tests

on:
  pull_request:
    branches: [main, stage]
    types: [opened, synchronize, reopened]

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run E2E tests
        run: yarn test:e2e
